import { printError, printLogInfo } from "/utils/print.js";

export const memberNamePrefix = "Keves #";

export const scriptHackingGang = "gangs/hacking_gang.js";
// TODO: not implemented yet
export const scriptCombatGang = "gang/combat_gang.js";

// Task lists
const tasksJsonHackingFilename = "data/gang_tasks_hacking.json";
const tasksJsonCombatFilename = "data/gang_tasks_combat.json";

//#region Tasks Files

/**
 * Writes gang tasks to a json file for other scripts to use.
 * Assumes player has already created a gang and tasks are available.
 *
 * @param {NS} ns
 * @param {boolean} isHackingGang : Hacking / Combat gang
 */
export function writeGangTasks(ns, isHackingGang = true) {
  const fname = "writeGangTasks";
  let tasks = ns.gang.getTaskNames().map((taskName) => {
    const task = ns.gang.getTaskStats(taskName);
    return task;
  });
  const filename = isHackingGang
    ? tasksJsonHackingFilename
    : tasksJsonCombatFilename;

  ns.write(filename, JSON.stringify(tasks, null, 2), "w");
  ns.printf(
    `[${fname}] ${isHackingGang ? "Hacking" : "Combat"} tasks written to ${filename}`,
  );
}

/**
 * Reads gang tasks from a json file.
 * Assumes player has already created a gang and tasks are available.
 * Assumes the tasks file has been generated by writeGangTasks function.
 *
 * @param {NS} ns
 * @param {boolean} isHackingGang : Hacking / Combat gang
 */
export function readGangTasks(ns, isHackingGang = true) {
  const fname = "readGangTasks";
  const filename = isHackingGang
    ? tasksJsonHackingFilename
    : tasksJsonCombatFilename;
  if (!ns.fileExists(filename)) {
    printError(
      ns,
      `[${fname}] Tasks file ${filename} does not exist. Please run the gangs/start.js script to generate the tasks file.`,
    );
    return [];
  }
  const tasksJson = ns.read(filename);
  const tasks = JSON.parse(tasksJson);
  ns.printf(
    `[${fname}] ${isHackingGang ? "Hacking" : "Combat"} tasks read from ${filename}`,
  );
  return tasks;
}

//#endregion Tasks Files

//#region Member Finder

// Hacking Level

/**
 * @summary Finds the gang member with the *lowest hacking* level.
 *
 * @param {NS} ns - Netscript API object
 * @param {string[]} memberNames - Array of gang member names to search through
 * @returns {GangMemberInfo} The member info object with the lowest hack stat
 * @throws Error if memberNames is empty
 */
export function findMemberLowestHackingLevel(ns, memberNames) {
  /** @type {GangMemberInfo[]} */
  const members = memberNames.map((memberName) =>
    ns.gang.getMemberInformation(memberName),
  );

  const bestMember = members.reduce((prev, current) => {
    return current.hack < prev.hack ? current : prev;
  });
  return bestMember;
}

/**
 * @summary Finds the gang member with the *highest hacking* level.
 *
 * @param {NS} ns - Netscript API object
 * @param {string[]} memberNames - Array of gang member names to search through
 * @returns {GangMemberInfo} The member info object with the highest hack stat
 * @throws Error if memberNames is empty
 */
export function findMemberHighestHackingLevel(ns, memberNames) {
  /** @type {GangMemberInfo[]} */
  const members = memberNames.map((memberName) =>
    ns.gang.getMemberInformation(memberName),
  );

  const bestMember = members.reduce((prev, current) => {
    return prev.hack < current.hack ? current : prev;
  });
  return bestMember;
}

/**
 * @summary Finds the gang member with the *highest wanted* level.
 *
 * @param {NS} ns - Netscript API object
 * @param {string[]} memberNames - Array of gang member names to search through
 * @returns {GangMemberInfo} The member info object with the highest wanted level
 * @throws Error if memberNames is empty
 */
export function findMemberHighestWantedLevel(ns, memberNames) {
  /** @type {GangMemberInfo[]} */
  const members = memberNames.map((memberName) =>
    ns.gang.getMemberInformation(memberName),
  );
  const bestMember = members.reduce((prev, current) => {
    return prev.wanted < current.wanted ? current : prev;
  });
  return bestMember;
}

//#endregion Member Finder
