import {
  equipmentJsonFilename,
  recruitmentMaxWaitTimeSeconds,
  tasksJsonCombatFilename,
  tasksJsonHackingFilename,
} from "./constants.js";
import { formatGainRate, formatTimeSeconds } from "/utils/formatters.js";
import { print, printError, toGreen, toRed } from "/utils/print.js";

function checkFileExists(ns, fname, type, filename) {
  if (ns.fileExists(filename)) {
    return true;
  }

  printError(
    ns,
    `[${fname}] ${type} file ${filename} does not exist. ` +
      `Please run the gangs/start.js script to generate the ${type} file.`,
  );

  return false;
}

//#region Tasks

/**
 * Writes gang tasks to a json file for other scripts to use.
 * Assumes player has already created a gang and tasks are available.
 *
 * @param {NS} ns
 * @param {boolean} isHackingGang : Hacking / Combat gang
 */
export function writeGangTasks(ns, isHackingGang = true) {
  const fname = "writeGangTasks";
  const filename = isHackingGang
    ? tasksJsonHackingFilename
    : tasksJsonCombatFilename;

  const tasks = ns.gang.getTaskNames().map((taskName) => {
    return ns.gang.getTaskStats(taskName);
  });

  ns.write(filename, JSON.stringify(tasks, null, 2), "w");

  // Log
  const gangType = isHackingGang ? "Hacking" : "Combat";
  ns.print(`[${fname}] ${toGreen(gangType)} tasks written to ${filename}`);
}

/**
 * Reads gang tasks from a json file.
 * Assumes player has already created a gang and tasks are available.
 * Assumes the tasks file has been generated by writeGangTasks function.
 *
 * @param {NS} ns
 * @param {boolean} isHackingGang : Hacking / Combat gang
 * @returns {GangTaskStats[]|null} Array of gang task stats objects.
 *   Null if file doesn't exist.
 */
export function readGangTasks(ns, isHackingGang) {
  const fname = "readGangTasks";
  const filename = isHackingGang
    ? tasksJsonHackingFilename
    : tasksJsonCombatFilename;

  if (!checkFileExists(ns, fname, "Tasks", filename)) {
    return null;
  }

  const tasksJson = ns.read(filename);
  const tasks = JSON.parse(tasksJson);

  // Log
  const gangType = isHackingGang ? "Hacking" : "Combat";
  ns.print(`[${fname}] ${toGreen(gangType)} tasks read from ${filename}`);

  return tasks;
}

//#endregion Tasks

//#region Equipment

/**
 * Creates an object containing information about all gang equipment.
 * To be used to write gang equipment to a json file and for gang information script.
 */
export function getGangEquipmentInformation(ns) {
  let augmentations = { hacking: [], combat: [] };
  let regular = { hacking: [], combat: [] };

  // Add equipment by type
  for (const equipmentName of ns.gang.getEquipmentNames()) {
    const type = ns.gang.getEquipmentType(equipmentName);
    const equipmentStats = ns.gang.getEquipmentStats(equipmentName);
    const cost = ns.gang.getEquipmentCost(equipmentName);
    const equipmentInfo = {
      name: equipmentName,
      type: type,
      cost: cost,
      stats: equipmentStats,
    };

    if (type === "Augmentation") {
      if (equipmentStats["hack"]) {
        augmentations.hacking.push(equipmentInfo);
      } else {
        augmentations.combat.push(equipmentInfo);
      }
    } else {
      if (equipmentStats["hack"]) {
        regular.hacking.push(equipmentInfo);
      } else {
        regular.combat.push(equipmentInfo);
      }
    }
  }

  // Costs
  function sumCost(equipmentList) {
    return equipmentList.reduce((sum, item) => sum + item.cost, 0);
  }
  const augmentationsHackingCost = sumCost(augmentations.hacking);
  const augmentationsCombatCost = sumCost(augmentations.combat);
  const regularHackingCost = sumCost(regular.hacking);
  const regularCombatCost = sumCost(regular.combat);

  const equipment = {
    augmentations: augmentations,
    regular: regular,
    augmentationsCosts: {
      hacking: augmentationsHackingCost,
      combat: augmentationsCombatCost,
    },
    regularCosts: {
      hacking: regularHackingCost,
      combat: regularCombatCost,
    },
  };
  return equipment;
}

/**
 * Writes gang equipment to a json file for other scripts to use.
 * Assumes player has already created a gang and equipment is available.
 *
 * @param {NS} ns
 * @returns {GangEquipment} The gang equipment object that was written to the file.
 *    See getGangEquipmentInformation for details on the structure of this object.
 */
export function writeGangEquipment(ns) {
  const fname = "writeGangEquipment";
  const filename = equipmentJsonFilename;

  const equipment = getGangEquipmentInformation(ns);
  ns.write(filename, JSON.stringify(equipment, null, 2), "w");
  ns.print(`[${fname}] Equipment object written to ${filename}`);

  return equipment;
}

export function readGangEquipment(ns) {
  const fname = "readGangEquipment";
  const filename = equipmentJsonFilename;

  if (!checkFileExists(ns, fname, "Equipment", filename)) {
    return null;
  }

  const equipmentJson = ns.read(filename);
  const equipment = JSON.parse(equipmentJson);
  ns.print(`[${fname}] Equipment read from ${filename}`);
  return equipment;
}

/**
 * Checks if we should buy equipment type (Augmentation or Equipment)
 * The calculations here are a rough estimate of whether the player has enough money.
 *
 * @param {NS} ns
 * @param {number} cost - the total cost of the equipment being considered
 * @param {{maxCostPercent: number, minCostPercent: number, type: string}} buyLimits -
 *    the cost limits for buying this type of equipment
 * @param {boolean} buyArgument - whether the user asked to buy this type of equipment
 * @returns {Promise<boolean>} true if we should buy this type of equipment, false otherwise
 */
export async function shouldBuy(ns, cost, buyLimits, buyArgument) {
  const playerMoney = ns.getPlayer().money;
  const costPercent = cost / Math.max(1, playerMoney);

  if (buyArgument) {
    if (costPercent < buyLimits.maxCostPercent) {
      return true;
    }

    function toBoldRed(text) {
      return `\x1b[1;31m${text}\x1b[0m`;
    }
    const formattedCostPercent = ns.formatPercent(costPercent, 5);
    const formattedThreshold = ns.formatPercent(buyLimits.maxCostPercent);
    const msgCost =
      toRed("cost (") +
      toBoldRed(formattedCostPercent) +
      toRed(") is above the threshold (" + formattedThreshold + ").");

    // Prompt the user
    // First close tail to make sure prompt is visible
    ns.ui.closeTail();
    const response = await ns.prompt(
      `${buyLimits.type} cost (${formattedCostPercent}) is above the threshold (${formattedThreshold}).\n` +
        `Do you want to buy ${buyLimits.type} for gang members anyway?`,
    );
    ns.ui.openTail();

    if (response) {
      print(
        ns,
        `✅ Buying ${toGreen(buyLimits.type)} for gang members. ${msgCost}`,
      );
      return true;
    } else {
      const msgAction = `Not buying ${buyLimits.type} for gang members.`;
      print(
        ns,
        `${toRed("❌")} ${toBoldRed(buyLimits.type)} ${msgCost} ${toBoldRed(msgAction)}`,
      );

      return false;
    }
  }

  // No buy argument provided, buy if cost is below min threshold
  if (costPercent < buyLimits.minCostPercent) {
    const formattedCostPercent = ns.formatPercent(costPercent, 5);
    const formattedThreshold = ns.formatPercent(buyLimits.minCostPercent);
    const msgCost = `✅ ${toGreen(buyLimits.type)} cost (${toGreen(formattedCostPercent)}) is below the threshold (${formattedThreshold})`;
    const msgAction = `${toGreen("Buying " + buyLimits.type + " for gang members")}.`;
    print(ns, `${msgCost}. ${msgAction}`);
    return true;
  }
  return false;
}

//#endregion Equipment

//#region Member Finder

/**
 * Finds the gang member with the min or max value of a given stat.
 *
 * @param {NS} ns - Netscript API object
 * @param {string[]} memberNames - Array of gang member names to search through
 * @param {string} stat - Property name on GangMemberInfo (e.g. "hack", "wantedLevelGain")
 * @param {"min"|"max"} direction - Whether to find the lowest or highest value
 * @returns {GangMemberInfo} The matching member info object
 * @throws {TypeError} if memberNames is empty
 */
function findMemberBy(ns, memberNames, stat, direction = "min") {
  /** @type {GangMemberInfo[]} */
  const members = memberNames.map((name) => ns.gang.getMemberInformation(name));
  return members.reduce((prev, cur) => {
    const pick =
      direction === "min" ? cur[stat] < prev[stat] : cur[stat] > prev[stat];
    return pick ? cur : prev;
  });
}

export const findMemberMinHackingLevel = (ns, memberNames) =>
  findMemberBy(ns, memberNames, "hack", "min");

export const findMemberMaxHackingLevel = (ns, memberNames) =>
  findMemberBy(ns, memberNames, "hack", "max");

export const findMemberMaxWantedLevel = (ns, memberNames) =>
  findMemberBy(ns, memberNames, "wantedLevelGain", "max");

export const findMemberMinWantedLevel = (ns, memberNames) =>
  findMemberBy(ns, memberNames, "wantedLevelGain", "min");

//#endregion Member Finder

/**
 * Finds the least productive member based on the sorted tasks list.
 * The least productive member is the one doing the task with the lowest focus gain.
 * If all members are doing the most productive task, then no member would be returned.
 *
 * @param {NS} ns
 * @param {string[]} memberNames
 * @param {GangTaskStats[]} sortedTasks - List of tasks sorted by focus gain (ascending)
 * @returns {{ member: GangMemberInfo, taskIdx: number }}
 *    member: The member doing the least productive task.
 *      Null if all members are doing the most productive task.
 *    taskIdx: The index of the task in the sortedTasks array.
 */
export function findLeastProductiveMember(ns, memberNames, sortedTasks) {
  const fname = "findLeastProductiveMember";

  /** @type {GangMemberInfo[]} */
  const members = memberNames.map((memberName) =>
    ns.gang.getMemberInformation(memberName),
  );

  let lowestGainingMember = null;
  let lowestTaskIdx = sortedTasks.length - 1;
  for (const member of members) {
    const taskIndex = sortedTasks.findIndex(
      (task) => task.name === member.task,
    );

    if (taskIndex === -1) {
      throw new Error(
        `[${fname}] Member ${member.name} is doing an unknown task: ${member.task}`,
      );
    }

    if (taskIndex < lowestTaskIdx) {
      lowestTaskIdx = taskIndex;
      lowestGainingMember = member;
    }
  }
  return { member: lowestGainingMember, taskIdx: lowestTaskIdx };
}

//#region Ascend

export function getShouldWaitAscend(ns, respectNeeded, respectGainRate) {
  const fname = "getShouldWaitAscend";

  if (respectGainRate <= 0) {
    // Respect is not increasing, no reason to wait to ascend
    return false;
  }

  // respect gain rate is per game cycle
  const respectGainRatePerSecond = respectGainRate * 5;
  const timeToNextRecruitSeconds = respectNeeded / respectGainRatePerSecond;

  const fmtRespectNeeded = ns.formatNumber(respectNeeded);
  const fmtRespectGainRate = formatGainRate(respectGainRatePerSecond);
  const fmtTimeToNextRecruit = formatTimeSeconds(timeToNextRecruitSeconds);
  ns.print(
    `[${fname}] Respect needed: ${fmtRespectNeeded}, gain rate: ${fmtRespectGainRate} ` +
      `=> Time to next recruit: ${fmtTimeToNextRecruit}.`,
  );

  return timeToNextRecruitSeconds <= recruitmentMaxWaitTimeSeconds;
}

//#endregion Ascend
