import { printError } from "/utils/print.js";

//#region Tasks Files

// Task lists
const tasksJsonHackingFilename = "data/gang_tasks_hacking.json";
const tasksJsonCombatFilename = "data/gang_tasks_combat.json";

/**
 * Writes gang tasks to a json file for other scripts to use.
 * Assumes player has already created a gang and tasks are available.
 *
 * @param {NS} ns
 * @param {boolean} isHackingGang : Hacking / Combat gang
 */
export function writeGangTasks(ns, isHackingGang = true) {
  const fname = "writeGangTasks";
  const tasks = ns.gang.getTaskNames().map((taskName) => {
    return ns.gang.getTaskStats(taskName);
  });
  const filename = isHackingGang
    ? tasksJsonHackingFilename
    : tasksJsonCombatFilename;

  ns.write(filename, JSON.stringify(tasks, null, 2), "w");
  ns.printf(
    `[${fname}] ${isHackingGang ? "Hacking" : "Combat"} tasks written to ${filename}`,
  );
}

/**
 * Reads gang tasks from a json file.
 * Assumes player has already created a gang and tasks are available.
 * Assumes the tasks file has been generated by writeGangTasks function.
 *
 * @param {NS} ns
 * @param {boolean} isHackingGang : Hacking / Combat gang
 */
export function readGangTasks(ns, isHackingGang = true) {
  const fname = "readGangTasks";
  const filename = isHackingGang
    ? tasksJsonHackingFilename
    : tasksJsonCombatFilename;
  if (!ns.fileExists(filename)) {
    printError(
      ns,
      `[${fname}] Tasks file ${filename} does not exist. Please run the gangs/start.js script to generate the tasks file.`,
    );
    return [];
  }

  const tasksJson = ns.read(filename);
  const tasks = JSON.parse(tasksJson);
  ns.printf(
    `[${fname}] ${isHackingGang ? "Hacking" : "Combat"} tasks read from ${filename}`,
  );
  return tasks;
}

//#endregion Tasks Files

//#region Member Finder

// Hacking Level

/**
 * Finds the gang member with the *lowest hacking* level.
 *
 * @param {NS} ns - Netscript API object
 * @param {string[]} memberNames - Array of gang member names to search through
 * @returns {GangMemberInfo} The member info object with the lowest hack stat
 * @throws {TypeError} if memberNames is empty
 */
export function findMemberLowestHackingLevel(ns, memberNames) {
  /** @type {GangMemberInfo[]} */
  const members = memberNames.map((memberName) =>
    ns.gang.getMemberInformation(memberName),
  );

  const bestMember = members.reduce((prev, current) => {
    return current.hack < prev.hack ? current : prev;
  });
  return bestMember;
}

/**
 * Finds the gang member with the *highest hacking* level.
 *
 * @param {NS} ns - Netscript API object
 * @param {string[]} memberNames - Array of gang member names to search through
 * @returns {GangMemberInfo} The member info object with the highest hack stat
 * @throws {TypeError} if memberNames is empty
 */
export function findMemberHighestHackingLevel(ns, memberNames) {
  /** @type {GangMemberInfo[]} */
  const members = memberNames.map((memberName) =>
    ns.gang.getMemberInformation(memberName),
  );

  const bestMember = members.reduce((prev, current) => {
    return prev.hack < current.hack ? current : prev;
  });
  return bestMember;
}

/**
 * Finds the gang member with the *highest wanted* level gain.
 *
 * @param {NS} ns - Netscript API object
 * @param {string[]} memberNames - Array of gang member names to search through
 * @returns {GangMemberInfo} The member info object with the highest wanted level gain
 * @throws {TypeError} if memberNames is empty
 */
export function findMemberHighestWantedLevel(ns, memberNames) {
  /** @type {GangMemberInfo[]} */
  const members = memberNames.map((memberName) =>
    ns.gang.getMemberInformation(memberName),
  );

  const bestMember = members.reduce((prev, current) => {
    return prev.wantedLevelGain < current.wantedLevelGain ? current : prev;
  });
  return bestMember;
}

/**
 * Finds the gang member with the *lowest wanted* level gain.
 *
 * @param {NS} ns - Netscript API object
 * @param {string[]} memberNames - list of members
 * @returns {GangMemberInfo} The member info object with the lowest wanted level gain
 * @throws {TypeError} if memberNames is empty
 */
export function findMemberLowestWantedLevel(ns, memberNames) {
  /** @type {GangMemberInfo[]} */
  const members = memberNames.map((memberName) =>
    ns.gang.getMemberInformation(memberName),
  );

  const bestMember = members.reduce((prev, current) => {
    return current.wantedLevelGain < prev.wantedLevelGain ? current : prev;
  });
  return bestMember;
}

//#endregion Member Finder

/**
 * Finds the least productive member based on the sorted tasks list.
 * The least productive member is the one doing the task with the lowest focus gain.
 * If all members are doing the most productive task, then no member would be returned.
 *
 * @param {NS} ns
 * @param {string[]} memberNames
 * @param {GangTaskStats[]} sortedTasks - List of tasks sorted by focus gain (ascending)
 * @returns {{ member: GangMemberInfo, taskIdx: number }}
 *    member: The member doing the least productive task.
 *      Null if all members are doing the most productive task.
 *    taskIdx: The index of the task in the sortedTasks array.
 */
export function findLeastProductiveMember(ns, memberNames, sortedTasks) {
  const fname = "findLeastProductiveMember";

  /** @type {GangMemberInfo[]} */
  const members = memberNames.map((memberName) =>
    ns.gang.getMemberInformation(memberName),
  );

  let lowestGainingMember = null;
  let lowestTaskIdx = sortedTasks.length - 1;
  for (const member of members) {
    const taskIndex = sortedTasks.findIndex(
      (task) => task.name === member.task,
    );

    if (taskIndex === -1) {
      throw new Error(
        `[${fname}] Member ${member.name} is doing an unknown task: ${member.task}`,
      );
    }

    if (taskIndex < lowestTaskIdx) {
      lowestTaskIdx = taskIndex;
      lowestGainingMember = member;
    }
  }
  return { member: lowestGainingMember, taskIdx: lowestTaskIdx };
}
